### ISSUE TITLE
Please stabilize the sort order of structures in noise settings

### ISSUE THREAD

**Issue by retep998** [misode/vanilla-worldgen#2]
They change their order every single version, so it would be great if their order could be stabilized somehow so the commits aren't as noisy.

**Comment by misode** [comment]
I agree this is a good suggestion. However unfeasible for this project, all I did was unzipped slicedlime's file and put them in this repo, with no processing.

Instead I implemented this in [mcmeta](https://github.com/misode/mcmeta) which is updated automatically and has stable ordering in these places. The `data-json` branch should be close to what this repository contained, but with some of the other data pack files.
